### ISSUE TITLE
segfault with Azure Linux 2.0

### ISSUE THREAD

**Issue by tofay** [microsoft/rust-symcrypt#25]
The bindings have been generated against a symcrypt 103.1.x header, but Azure Linux 2.0 includes SymCrypt 103.0.1, so symcrypt immediately segfaults on that distro.

Since no bindings are generated for symcrypt 103.1 additions, can you regenerate the bindings using 103.0?

I'm also happy to submit a patch that adds a bindgen feature to symcrypt-sys, so users can run bindgen, but I'm not sure what the intended rust-symcrypt / symcrypt version compatibility is.

**Comment by nnmkhang** [comment]
Hi Tom, thanks for this comment, I remembered we followed up offline over email. Going forward we will not be supporting AL2 and are requiring users to be on AL3.
